<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Javier Zialcita">

<title>Arsenal 2024/25 Shot Analysis Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-a1ff8711b79ae3724c050874b28d9907.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#arsenals-shooting-profile" id="toc-arsenals-shooting-profile" class="nav-link" data-scroll-target="#arsenals-shooting-profile">Arsenal’s Shooting Profile</a></li>
  <li><a href="#how-opponents-defended-arsenal" id="toc-how-opponents-defended-arsenal" class="nav-link" data-scroll-target="#how-opponents-defended-arsenal">How Opponents Defended Arsenal</a></li>
  <li><a href="#arsenals-chance-creation" id="toc-arsenals-chance-creation" class="nav-link" data-scroll-target="#arsenals-chance-creation">Arsenal’s Chance Creation</a></li>
  <li><a href="#individual-shot-creation-and-dribbling" id="toc-individual-shot-creation-and-dribbling" class="nav-link" data-scroll-target="#individual-shot-creation-and-dribbling">Individual Shot Creation and Dribbling</a></li>
  <li><a href="#transition-attacking" id="toc-transition-attacking" class="nav-link" data-scroll-target="#transition-attacking">Transition Attacking</a></li>
  <li><a href="#transfer-recommendation-eberechi-eze" id="toc-transfer-recommendation-eberechi-eze" class="nav-link" data-scroll-target="#transfer-recommendation-eberechi-eze">Transfer Recommendation: Eberechi Eze</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Arsenal 2024/25 Shot Analysis Report</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Javier Zialcita </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Going into the 2024/25 season, Arsenal were meant to be the favorites to win the Premier League, after finishing 2nd in back to back seasons. But ultimately, despite a deep run in the Champions League, their inconsistency in the Premier League was a shock to many. Specifically, despite their defense still being solid, their attacking numbers declined way more from the 2023/24 season prior.</p>
<p>In this report, with a dataframe of almost all the shots Arsenal took in the 24/25 Premier League season, I will highlight their strengths and weaknesses from the season, and what the team can change before the season starts.</p>
</section>
<section id="arsenals-shooting-profile" class="level1">
<h1>Arsenal’s Shooting Profile</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  total_shots goals avg_xg
        &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
1         291    63   0.18</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  result                   n
  &lt;chr&gt;                &lt;int&gt;
1 off target              95
2 saved                   75
3 goal                    63
4 blocked                 47
5 deflected off target    10
6 own goal                 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  player                 n
  &lt;chr&gt;              &lt;int&gt;
1 Leandro Trossard      39
2 Bukayo Saka           33
3 Declan Rice           30
4 Gabriel Martinelli    28
5 Kai Havertz           27
6 Mikel Merino          25</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  assist_type       n
  &lt;chr&gt;         &lt;int&gt;
1 normal pass     108
2 floated cross    33
3 n/a              33
4 corner           29
5 through ball     21
6 driven cross     19</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
   zone     n
  &lt;dbl&gt; &lt;int&gt;
1     2   117
2     1    54
3     3    37
4     4    34
5     5    28
6     7     8</code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/shot-zones.png" class="img-fluid figure-img" style="width:30.0%"></p>
<figcaption>Shot Zones</figcaption>
</figure>
</div>
<p>From the diagram and information above, we can tell that a majority of Arsenal’s shots are central and inside the box. Out of 291 shots from open play, Arsenal scored 63, which is an 18% conversion rate.</p>
</section>
<section id="how-opponents-defended-arsenal" class="level1">
<h1>How Opponents Defended Arsenal</h1>
<p>The narrative around Arsenal being favorites may have caused other teams’ defensive styles of play against them to change.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  defensive_line total percentage
  &lt;chr&gt;          &lt;int&gt;      &lt;dbl&gt;
1 high              37       12.7
2 low              165       56.7
3 mid               89       30.6</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/defensive-traffic-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now that Arsenal are favorites, Premier League teams “respect” them more, meaning they give Arsenal more space to play out the back and advance towards the opposing teams’ box. This usually means they sit deeper and give Arsenal more space in their own defensive third, allowing them to build out from the back with relative ease.</p>
<p>However, as soon as Arsenal approaches the final third, all that space disappears. Opponents put more defenders between the ball and the goal, making it harder for Arsenal to pass and create more threatening shots.</p>
<p>As seen from the histogram, teams mostly have at least 5 players excluding the goalkeeper defending the goal in their own box whenever Arsenal take a shot.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/brentford-defending.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Defending example</figcaption>
</figure>
</div>
<p>As one can see in the photo above from Arsenal vs Brentford in January, Brentford had all their players behind the ball. This made it very difficult for Arsenal to create a shot that was very likely to score.</p>
<p>As a result, teams often get pressure on the player shooting.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  xg by shot_under_pressure
t = 3.624, df = 168.66, p-value = 0.0003838
alternative hypothesis: true difference in means between group no and group yes is not equal to 0
95 percent confidence interval:
 0.04350852 0.14762971
sample estimates:
 mean in group no mean in group yes 
        0.2401887         0.1446196 </code></pre>
</div>
</div>
<p>Shots taken under defensive pressure had an average xG of 0.14, while shots without pressure had an average xG of 0.24. This difference is large enough that it is very unlikely to be due to chance, showing that pressure greatly reduces the quality of Arsenal’s chances.</p>
</section>
<section id="arsenals-chance-creation" class="level1">
<h1>Arsenal’s Chance Creation</h1>
<p>To find what areas Arsenal attack in better than others in possession, I divided the area into 5 spaces: the left halfspace, right halfspace, middle, left, and right. I also looked at shots from set pieces, which are restarts that the referee awards, such as corner kicks and free kicks.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  entry_type      count   prop
  &lt;chr&gt;           &lt;int&gt;  &lt;dbl&gt;
1 left               49 0.181 
2 left halfspace     37 0.137 
3 middle             27 0.0996
4 right              50 0.185 
5 right halfspace    48 0.177 
6 set piece          60 0.221 </code></pre>
</div>
</div>
<p>From the table, we see that Arsenal are mostly reliant on attacking from the wings and right halfspace, with less emphasis on the left halfspace and middle. This makes sense because players such as Saka, Odegaard, Martinelli, and Trossard often take up these spaces.</p>
<p>This season, Arsenal were also known to heavily rely on set pieces in tight games.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.22222</code></pre>
</div>
</div>
<p>In fact, 22.2% of Arsenal’s goals were from set pieces. As a team that is supposed to dominate games, this is concerning because it highlights how uninspired Arsenal’s creation was from open play relative to prior seasons.</p>
</section>
<section id="individual-shot-creation-and-dribbling" class="level1">
<h1>Individual Shot Creation and Dribbling</h1>
<p>From a fan’s perspective, a lot of Arsenal’s lack of creation stems from the fact that they do not have enough world-class playmakers. Many players depend on the system rather than creating big chances by themselves. To gain insight into this, I checked how often players dribble before shots.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/touches-before-shot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For starters, the majority of Arsenal’s shots were first-time shots, meaning players either did not touch the ball before shooting or only took one touch to control it. This suggests that Arsenal players rarely created shots for themselves. They had to rely on movement and passing to score.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  total_shots shots_after_beating_defender proportion
        &lt;int&gt;                        &lt;int&gt;      &lt;dbl&gt;
1         291                           67      0.230</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  total_goals goals_after_beating_defender proportion
        &lt;int&gt;                        &lt;int&gt;      &lt;dbl&gt;
1          63                           15      0.238</code></pre>
</div>
</div>
<p>About 22% of Arsenal’s goals and shots came after an Arsenal player beat a defender on the dribble. For Arsenal to succeed offensively and score more goals, this number should go up next season.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
   beaten_by          times_beaten_defender proportion
   &lt;chr&gt;                              &lt;int&gt;      &lt;dbl&gt;
 1 Bukayo Saka                           20     0.299 
 2 Gabriel Martinelli                    10     0.149 
 3 Leandro Trossard                       8     0.119 
 4 Ethan Nwaneri                          6     0.0896
 5 Martin Odegaard                        6     0.0896
 6 Declan Rice                            5     0.0746
 7 Jurrien Timber                         5     0.0746
 8 Gabriel Jesus                          2     0.0299
 9 Raheem Sterling                        2     0.0299
10 Ben White                              1     0.0149
11 Myles Lewis-Skelly                     1     0.0149
12 Riccardo Calafiori                     1     0.0149</code></pre>
</div>
</div>
<p>From the table, we see that Bukayo Saka beat the most players one-on-one despite missing half the season through injury. Despite that injury, he still had more defender-beating actions than Gabriel Martinelli and Leandro Trossard. This supports the idea that Arsenal’s attack depends heavily on Saka.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/wing-entry-xg-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I observed that the right side tends to produce higher upper-end xG chances, though this difference was not statistically significant. This may suggest potential but inconsistent quality from the right.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 6
   zone p_value mean_beaten mean_not_beaten n_beaten n_not_beaten
  &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;           &lt;dbl&gt;    &lt;int&gt;        &lt;int&gt;
1     1  0.0555      0.638           0.390         4           23
2     2  0.811       0.204           0.199        25           68
3     3  0.277       0.0782          0.129        11           23
4     4  0.399       0.0692          0.0711       12           19
5     5  0.263       0.05            0.0395        6           19
6     6  1           0.035           0.03          4            1
7     8  1           0.02            0.02          2            4</code></pre>
</div>
</div>
<p>To evaluate whether Arsenal creates more dangerous chances when attackers beat defenders on the dribble, I compared xG in situations where a defender was beaten versus when they were not. In zone 1, the p-value is almost significant. In the small sample size, when Arsenal players beat their defender and pass into the box, it is often very dangerous.</p>
<p><a href="https://youtu.be/62DBSHviDYY?si=A_4GZ9vwrz50L_ms&amp;t=88">Arsenal vs Ipswich GW18 — Saka dribble in zone 1</a></p>
</section>
<section id="transition-attacking" class="level1">
<h1>Transition Attacking</h1>
<p>With Arsenal struggling to score against low blocks, the ability to capitalize on transition goals is important.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  total average_xg average_time_to_shoot num_goals goals_prop
  &lt;int&gt;      &lt;dbl&gt;                 &lt;dbl&gt;     &lt;int&gt;      &lt;dbl&gt;
1    36      0.180                  6.09        11      0.306</code></pre>
</div>
</div>
<p>Some fans believe Arsenal were too slow in transition compared to seasons prior. The average xG from transitions is higher than the total average, but the time to shoot is pretty long, which makes it easier for defenders to get back and protect their goal. Overall, Arsenal’s transition play lacked creativity, decision making, and efficiency.</p>
<p><a href="https://youtu.be/siDxiv91yTI?si=EMSB9jd4TNkVSauI">Arsenal transition example — Martinelli GW decision making</a></p>
<p>As seen in the clip, Martinelli makes a poor decision to shoot while the defender is recovering to block the goal. He also does not have strong passing options for a better shot. This was a common theme throughout the season.</p>
</section>
<section id="transfer-recommendation-eberechi-eze" class="level1">
<h1>Transfer Recommendation: Eberechi Eze</h1>
<p>After this season, many fans believed the main target should be a left winger. After playing around with the data, I believe the data supports this. Not everything was statistically significant, but football is a game of small margins.</p>
<p>The player Arsenal have been linked with is Eberechi Eze. Eze is a talented playmaker, dribbler, and finisher. The main concern is that he is primarily a central attacking midfielder and not a traditional touchline winger.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 3
   zone shots proportion
  &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;
1     2    15     0.385 
2     4    11     0.282 
3     1     6     0.154 
4     3     3     0.0769
5     7     2     0.0513
6     5     1     0.0256
7     8     1     0.0256</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
   zone shots proportion
  &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;
1     2    12     0.429 
2     4     7     0.25  
3     1     6     0.214 
4     3     2     0.0714
5     6     1     0.0357</code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/eberechi-eze-heatmap.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Eberechi Eze 2023/2024 Heatmap</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/gabriel-martinelli-heatmap.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Gabriel Martinelli 2024/2025 Heatmap</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/leandro-trossard-heatmap.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Leandro Trossard 2024/2025 Heatmap</figcaption>
</figure>
</div>
<p>From the heatmaps, we can see that all three players have a lot of touches on the touchline. Although Eze operated more frequently in the middle of the field, he has enough experience in wide areas to be useful for Arsenal on the left.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/eberechi-eze-shotmap.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Eberechi Eze 2024/2025 Shotmap</figcaption>
</figure>
</div>
<p>Knowing Eze as a player and seeing both his heatmap and shotmap, I would say that he “generates football.” What that means is that no matter where he plays, he usually finds a way to make an impact. He can shoot, dribble, and pass in the middle and left part of the field.</p>
<p><a href="https://youtu.be/ocwPznvEyqk?si=akr-F37EoKj9Nomt&amp;t=423">Eze left-side cross</a></p>
<p><a href="https://youtu.be/ocwPznvEyqk?si=ZGSb3zYD68OXvGRn&amp;t=510">Eze driving inside and creating space</a></p>
<p>Outside of the numbers and maps, these clips show Eze’s ability to play on the left. In the first clip, he plays a strong cross from the touchline. In the second clip, he receives the ball on the left, drives inside, attracts defenders, and opens space for a teammate.</p>
<p>This type of player would help lighten the load on Saka and make Arsenal’s attack less predictable.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Arsenal remained strong defensively during the 2024/25 season, but their attack became too predictable. Opponents defended deeper, Arsenal relied heavily on set pieces, and Bukayo Saka carried too much of the team’s individual creation. While some results were limited by sample size, the overall patterns suggest Arsenal would benefit from adding another creative dribbler on the left side. Based on the data and tactical evidence, Eberechi Eze appears to be a strong fit for that need.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>